Repository RajveerSodhi/EduPool, pull requests merged in 2024-03, with the labels that each got.

#127 added teacher instance to show in the enrollments table
  flask/instance/database.db
  flask/website/views.py
Labels: back-end

#142 Add edit page
  flask/website/templates/EditDetails
Labels: front-end

#171 Discussion page has been added
  flask/website/models.py
  flask/website/static/css/discussion.css
  flask/website/templates/course.html
  flask/website/templates/discussion.html
  flask/website/views.py
Labels: front-end, back-end

#172 Front end for the Reply page
  flask/website/templates/reply.html
Labels: front-end

#179 integrate reply with database and discussion page
  flask/website/templates/discussion_detail.html
Labels: front-end

#203 change username to email and add autentication
  flask/website/templates/login.html
  flask/website/templates/signup.html
Labels: Front-end feature
