Repository RajveerSodhi/EduPool, pull requests merged in 2024-04, with the labels that each got.

#237 Add Css for the Course page
  flask/instance/database.db
  flask/website/static/blacklogo.svg
  flask/website/static/css/discussion.css
  flask/website/static/css/discussion_detail.css
  flask/website/templates/course.html
  flask/website/templates/sidebar.html
  flask/website/templates/signup.html
Labels: front-end

#272 Placeholder
  flask/website/templates/EditDetails.html
Labels: Front-end feature

#280 Painted w0lf/issue275
  flask/website/templates/EditDetails.html
  flask/website/views.py
Labels: front-end

#294 Sign up and Enroll into Courses fixes
  flask/website/templates/EnrollCourse.html
  flask/website/templates/signup.html
Labels: front-end, Front-end feature

#297 Added hashing for update password
  flask/website/templates/home.html
  flask/website/views.py
Labels: front-end, back-end

#298 Joined tables to show courses and id for accept offer
  flask/website/templates/acceptCourse.html
  flask/website/views.py
Labels: front-end, back-end

#300 Added route after course creation submission
  flask/website/static/css/createCourse.css
  flask/website/views.py
Labels: back-end

#301 Admin cannot submit an assignment and display message for submission for grading
  flask/website/templates/course.html
  flask/website/templates/essay.html
  flask/website/templates/quiz.html
Labels: front-end

#306 Display already submitted for essay
  flask/website/templates/essay.html
  flask/website/views.py
Labels: front-end

#307 Bug fix
  flask/website/templates/createAssignment.html
  flask/website/templates/essay.html
  flask/website/views.py
Labels: front-end, back-end

#326 Added changed that caused issue to grade student submissions
  flask/website/templates/gradeEssay.html
  flask/website/views.py
Labels: back-end

#324 added css changes to discussion and discussion details for uniformity
  flask/website/static/css/discussion.css
  flask/website/static/css/discussion_detail.css
  flask/website/templates/discussion.html
  flask/website/templates/discussion_detail.html
  flask/website/views.py
Labels: front-end

#313 added constraint to essay submission so that texr/file is required
  flask/website/static/css/createAssignment.css
  flask/website/static/css/gradeAssignment.css
  flask/website/static/css/viewGrade.css
  flask/website/templates/essay.html
  flask/website/templates/viewGrade.html
Labels: front-end

#305 Add password validation and confirmation fields in EditDetails.html
  flask/website/templates/EditDetails.html
Labels: Front-end feature

#332 added some css edits for discussion page for better look
  flask/website/static/css/discussion.css
  flask/website/static/css/discussion_detail.css
  flask/website/templates/discussion_detail.html
Labels: front-end

#336 more css changes
  flask/website/static/css/createAssignment.css
  flask/website/templates/acceptCourse.html
  flask/website/templates/createAssignment.html
Labels: front-end

#339 Fix required field in password field + Signup dataset for all users
  flask/instance/database.db
  flask/website/templates/EditDetails.html
Labels: back-end

#340 resolved enroll into course issue and added sidebar to remaining pages
  flask/instance/database.db
  flask/website/static/css/createCourse.css
  flask/website/static/css/gradeAssignment.css
  flask/website/templates/acceptCourse.html
  flask/website/templates/createCourse.html
  flask/website/templates/gradeQuiz.html
  flask/website/views.py
Labels: front-end, back-end

#341 Added indentation for sub assignments
  flask/website/templates/course.html
  flask/website/templates/home.html
Labels: front-end

#342 css changes for gradeAssignments
  flask/website/static/css/gradeAssignment.css
Labels: front-end

#345 final changes for fluid app functionality
  flask/website/templates/createAssignment.html
  flask/website/templates/quiz.html
  flask/website/views.py
Labels: front-end, back-end

#347 Quiz bug
  flask/website/templates/createAssignment.html
  flask/website/templates/gradeQuiz.html
  flask/website/views.py
Labels: front-end, back-end

#350 Removed max grade for quiz
  flask/website/templates/createAssignment.html
  flask/website/templates/gradeQuiz.html
Labels: front-end

#352 proper feedback for course creation
  flask/website/templates/createCourse.html
Labels: front-end
